spring:
  application:
    name: hzero-workflow-plus
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_workflow_plus?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  redis:
    host: ${SPRING_REDIS_HOST:redis.hzero.org}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:1}
  freemarker:
    request-context-attribute: base  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    cache: true #缓存配置
    template-loader-path: classpath:/static/ #模板加载路径
    charset: UTF-8
    expose-request-attributes: true
#choerodon:
#  ldap:
#    userNameType: 0
#  devops:
#    message: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS:40000}
  stream:
    queue:
      enabled: false
ribbon:
  ReadTimeout: ${RIBBON_READ_TIMEOUT:30000}
  ConnectTimeout: ${RIBBON_CONNECT_TIMEOUT:3000}
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true

hzero:
  scheduler:
    # 配置执行器编码 客户端就会向服务端自动注册
    executor-code: HWFP_EXECUTOR
    # 手动配置无线网卡ip（不需要加上端口号，端口号自动读取）不配置访问对应的api会出现网络超时或者500错误
  workflow:
    hr-service-name: hzero-platform
    activiti:
      mail-server-host: ${HZERO_WORKFLOW_MAIL_HOST:stmp.163.com}
      mail-server-port: ${HZERO_WORKFLOW_MAIL_PORT:25}
      mail-server-username: ${HZERO_WORKFLOW_MAIL_USERNAME:hzero@163.com}
      mail-server-password: ${HZERO_WORKFLOW_MAIL_PASSWORD:hzero}
      database-type: ${DATABASE_TYPE:mysql}
    engineUrl: ${HZERO_WORKFLOW_SERVICE_URL:http://dev.hzero.org:8080/hwfp}
  lov:
    sql:
      enabled: true
    value:
      enabled: true
  resource:
    # 匹配的资源才会解析JwtToken便于得到UserDetails
    pattern: ${HZERO_RESOURCE_PATTERN:/v1/*,/hzero/*,/hwfp/v1/*,/hwfp/hzero/*}
  modular:
    enable: false
logging:
  level:
    org.hzero.workflow: ${LOG_LEVEL:debug}
    org.activiti: ${LOG_LEVEL:debug}